# Generated by Django 4.0.6 on 2022-08-03 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_url',
            field=models.FileField(upload_to='uploaded/document/', validators=[django.core.validators.FileExtensionValidator(['csv', 'xlsx', 'xls'], 'Only csv, xlsx, xls files are allowed')]),
        ),
    ]
