# Generated by Django 4.0.6 on 2022-08-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='temp')),
            ],
        ),
    ]
